# NightStalker Example Configuration
# Copy this file to nightstalker_config.yaml and customize

framework:
  name: "NightStalker"
  version: "1.0.0"
  mode: "stealth"
  log_level: "INFO"

# Exfiltration Configuration
exfiltration:
  primary_method: "dns"
  
  # DNS Exfiltration (No server required)
  dns:
    enabled: true
    domain: "your-domain.com"  # Replace with your domain
    chunk_size: 50
    delay_between_chunks: 1.0
    
  # HTTPS Exfiltration
  https:
    enabled: true
    target_url: "https://httpbin.org/post"  # Test endpoint
    
  # GitHub Gist Exfiltration
  github_gist:
    enabled: false
    gist_id: "your-gist-id"  # Your private gist ID
    token: "your-github-token"  # Your GitHub personal access token
    
  # Telegram Bot Exfiltration
  telegram:
    enabled: false
    bot_token: "your-bot-token"  # From @BotFather
    chat_id: "your-chat-id"  # Your chat ID

# Payload Builder Configuration
payload_builder:
  default_format: "python"
  compression_enabled: false
  encryption_enabled: false
  obfuscation_enabled: false

# Stealth Configuration
stealth:
  traffic_blending:
    enabled: true
  rate_limiting:
    enabled: true
    requests_per_minute: 10

# Profiles for different scenarios
profiles:
  stealth:
    exfiltration:
      primary_method: "dns"
      dns:
        enabled: true
      https:
        enabled: false
        
  aggressive:
    exfiltration:
      primary_method: "https"
      https:
        enabled: true
      dns:
        enabled: true
    stealth:
      rate_limiting:
        enabled: false 